import { Product } from "@/types";

// Note: All image URLs have been verified to exist as of April 2026.
export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Funda Silicone Premium - iPhone 14",
    description: "Silicona líquida suave, acabado mate y protección interna de terciopelo. Varios colores.",
    price: 4500,
    imageUrl: "/img/Funda Silicone Premium.jpg",
    category: "Fundas",
  },
  {
    id: "2",
    name: "Cargador Rápido 25W PD - Samsung",
    description: "Carga Super Rápida 2.0 para dispositivos Galaxy. Incluye cable USB-C a C.",
    price: 8900,
    imageUrl: "/img/Cargador Rápido 25W.jpg",
    category: "Cargadores",
  },
  {
    id: "3",
    name: "Protector de Pantalla Cerámico",
    description: "Material cerámico flexible e irrompible. Máxima dureza contra rayones.",
    price: 2500,
    imageUrl: "/img/Protector de Pantalla.jpg",
    category: "Protectores",
  },
  {
    id: "4",
    name: "Auriculares Bluetooth TWS i12",
    description: "Conexión estable, controles táctiles y estuche de carga compacta. Sonido nítido.",
    price: 12500,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=800&auto=format&fit=crop",
    category: "Audio",
  },
  {
    id: "5",
    name: "Cable Lightning iPhone Trenzado",
    description: "1.5 metros de largo, refuerzo de nylon contra tirones. Certificación MFi.",
    price: 3800,
    imageUrl: "/img/Cable Lightning iPhone.jpg",
    category: "Cables",
  },
  {
    id: "6",
    name: "Soporte Magnético Rejilla Auto",
    description: "Imán de neodimio ultra potente. Compatible con cualquier tipo de ventila.",
    price: 4200,
    imageUrl: "/img/Soporte Magnético Rejill.jpg",
    category: "Soportes",
  },
  {
    id: "7",
    name: "Funda Transparente Antichoque",
    description: "Esquinas reforzadas con Air-Cushion. No se pone amarilla con el tiempo.",
    price: 3200,
    imageUrl: "/img/Funda Transparente.jpg",
    category: "Fundas",
  },
  {
    id: "8",
    name: "Power Bank Slim 10000mAh",
    description: "Cargador portátil ultra delgado con indicador LED de carga y carga rápida.",
    price: 18900,
    imageUrl: "/img/Power Bank Slim.jpg",
    category: "Cargadores",
  },
  {
    id: "9",
    name: "Funda Leather MagSafe iPhone",
    description: "Cuero sintético premium con imanes incorporados para carga MagSafe perfecta.",
    price: 11500,
    imageUrl: "/img/Funda Leather MagSafe.jpg",
    category: "Fundas",
  },
  {
    id: "10",
    name: "Smartwatch Deportivo Band 7",
    description: "Pantalla AMOLED, monitoreo de oxígeno en sangre y 120 modos deportivos.",
    price: 24500,
    imageUrl: "https://images.unsplash.com/photo-1544117519-31a4b719223d?q=80&w=800&auto=format&fit=crop",
    category: "Accesorios",
  },
  {
    id: "11",
    name: "Aro de Luz LED para Selfies",
    description: "Clip universal para celular. 3 niveles de brillo para fotos perfectas.",
    price: 3500,
    imageUrl: "/img/Aro de Luz LED para.jpg",
    category: "Accesorios",
  },
  {
    id: "12",
    name: "Adaptador Jack 3.5mm a USB-C",
    description: "Conecta tus auriculares de siempre en tu teléfono de última generación.",
    price: 2200,
    imageUrl: "/img/Adaptador Jack 3.5mm.jpg",
    category: "Cables",
  },
  {
    id: "13",
    name: "Funda Flip Case con Billetera",
    description: "Protección 360 y espacio para 3 tarjetas. Cierre magnético seguro.",
    price: 6800,
    imageUrl: "/img/Funda Flip Case.png",
    category: "Fundas",
  },
  {
    id: "14",
    name: "Trípode Bluetooth Extensible",
    description: "Se convierte en palo de selfie y trípode de mesa. Control remoto incluido.",
    price: 9500,
    imageUrl: "/img/Trípode Bluetooth.webp",
    category: "Soportes",
  },
  {
    id: "15",
    name: "Lentes de Cámara Protectoras",
    description: "Vidrio templado individual para cada lente. No afecta la calidad de fotos.",
    price: 2900,
    imageUrl: "/img/Vidrio templado individual para cada lente.webp",
    category: "Protectores",
  },
  {
    id: "16",
    name: "Cable USB-C a USB-C 60W",
    description: "Ideal para carga de tablets y smartphones de alta gama. 2 metros.",
    price: 4500,
    imageUrl: "/img/Cable Usb C A C 60w.webp",
    category: "Cables",
  },
  {
    id: "17",
    name: "Tarjeta MicroSD 128GB Clase 10",
    description: "Expande la memoria de tu dispositivo. Ideal para video 4K.",
    price: 13900,
    imageUrl: "/img/Tarjeta MicroSd 128gb clase 10.webp",
    category: "Accesorios",
  },
  {
    id: "18",
    name: "Funda de Silicón Neón",
    description: "Colores vibrantes y material soft-touch. Protege contra caídas leves.",
    price: 4200,
    imageUrl: "/img/Funda de Silicón neon.webp",
    category: "Fundas",
  },
  {
    id: "19",
    name: "Limpiador de Pantallas Nano-Tech",
    description: "Kit con spray antimicrobiano y paño premium. Sin rastros de grasa.",
    price: 1800,
    imageUrl: "/img/Limpiador de pantalla nano-tech.png",
    category: "Limpieza",
  },
  {
    id: "20",
    name: "Soporte de Mesa Ajustable",
    description: "Ideal para videollamadas o ver series. Plegable y antideslizante.",
    price: 3900,
    imageUrl: "/img/soporte de mesa ajustable.webp",
    category: "Soportes",
  },
];
